### ISSUE TITLE
traktflix not listing trakt.tv play dates after sync

### ISSUE THREAD

**Issue by joyrider3774** [tegon/traktflix#50] opened 2017-04-04 09:45 UTC
Hi,

I just synced a lot of shows with my trakt.tv account using the history sync for some reason it displayed 0 movies and 0 shows synced at the end, however when i go to my trakt.tv account / website i do see the plays were registered so i don't want to sync them again since i had this problem in the past when doing the sync a second time the plays get duplicated on the trakt.tv site.

Now the problem is whenever i use the history sync the traktflix plugin is not listing the play dates from from trakt.tv even though the play dates are there.

So it seems to me there are 2 problems:
1) it sometimes seems to sync history but displays it did not sync anything even though the plays are being registered in the trakt
2) if the above happens history sync want's to sync them again because for some reason even though they did get registered in point 1 but traktflix said it did not sync anything it is not listing the play dates so it can't compare the data.

are there any log files being generated if so where so i can have a look at them or supply them ?

**Comment by tegon** [comment] 2017-04-05 12:49
Hi, that seems odd. I just tested here and it showed correctly how many episodes were added.

One thing that is happening - and I will fix it - is that right after you sync, the items don't update in the view. So it still shows no date in Trakt but it is already synced. If you reload the page it should appear synced. Does it still look like it is not synced after you reload?

For problem number 1, I display how many episodes and movies were added based on the response from Trakt's API. You can open your console on the network tab and look for this request (after hitting sync now):

![screenshot 2017-04-05 09 18 53](https://cloud.githubusercontent.com/assets/3727827/24705183/27cfa14c-19e1-11e7-8d24-d105429e3b14.png)
![screenshot 2017-04-05 09 19 02](https://cloud.githubusercontent.com/assets/3727827/24705184/27d64272-19e1-11e7-9349-02aba9c8083b.png)

On number two: Traktflix considers an item as synced if it has a play on Trakt.tv on the same day as Netflix. Here is a sample request:

First, the item from Netflix:
![screenshot 2017-04-05 09 26 42](https://cloud.githubusercontent.com/assets/3727827/24705794/d5900ec8-19e3-11e7-8e7b-86cb8a71f47b.png)
![screenshot 2017-04-05 09 41 47](https://cloud.githubusercontent.com/assets/3727827/24705900/2508f6b8-19e4-11e7-9005-8bc83fd05b3e.png)

Then we check Trakt's history:
![screenshot 2017-04-05 09 27 58](https://cloud.githubusercontent.com/assets/3727827/24705744/9f53725a-19e3-11e7-99de-d9f36a61bb1e.png)
![screenshot 2017-04-05 09 28 09](https://cloud.githubusercontent.com/assets/3727827/24705743/9f53aa0e-19e3-11e7-82d1-ef512d23a75a.png)

And I compare they like this: https://jsbin.com/juhitogaho/edit?js,console

Anyway, this is a very long comment 😅 . If you can check these requests and put the results here, it will help to find the cause of this problem.

Thanks.

**Comment by joyrider3774** [comment] 2017-04-06 13:05
Hi @tegon,

thanks for the lengthy explanation. Here is some more information ...

I tested it at home yesterday and there i had no problem but will make sure tonight again as i hadn't looked in depth. 

But at work it gives me problems. I do know we have a checkpoint (hardware / firewall) in place so it could be the firewall is blocking things although the trakt.tv site works perfectly when browsing it from work and traktflix does seem to be able to get some dates of other episodes i synced in the past.

These errors i noticed initially at work .. It's probably some errors trying to get the images of the shows ...
![image](https://cloud.githubusercontent.com/assets/10714776/24754577/5773a3d4-1ad7-11e7-90e3-3c3709bd3347.png) and might be unrelated they also don't happen every time when i refresh the page 

Then i looked at the trakt api calls... There is one problem i have no way to know what episode id corresponds to which episode / series.. So I'm unable to find the specific call for it in the network list..  Is there a way to find out the episode id of a certain episode while browsing the trackt.tv website ? so i can more specifically find out the requests being made for that specific episode ? i do see some 304's, 204's and 200's as you can see in the screenshot below.
in the screenshot below those episodes are synced (for the ones there is a trakt.tv url found) but traktflix doesn't seem to display it
![image](https://cloud.githubusercontent.com/assets/10714776/24755164/6fbb59bc-1ad9-11e7-900d-76c1a47555b9.png)

but if i look further down it does show some synced from a previous sync although i can't remember if i synced them from home ore work .. so maybe our firewall is not blocking things or is the browser reading cached results somehow
![image](https://cloud.githubusercontent.com/assets/10714776/24755220/9fdbc294-1ad9-11e7-992e-5770c63278f5.png)

Does traktflix make an api call for every item listed in history ? or does it keep some data about syncs somwhere as well ? 

If i could figure out a way to find out which episode id is which episode on trakt.tv i could find out the specific entry in the network settings of chrome as now i have no clue which one to look for.

**Comment by joyrider3774** [comment] 2017-04-06 13:50
okay if figured out a way to know the episode id based on the episode page i'm viewing in trakt.tv if you do view source while being on the episode page you see a meta tag with screenshot url..
for example for hemlock grove seasons 1 epsidoe 13 it shows
```
<meta property="og:image" content="https://walter.trakt.tv/images/episodes/000/886/087/screenshots/thumb/42b1172c7d.jpg"/>
```
the id is then 886087

if i look this call up it seems trakt api itselve returns empty values
![image](https://cloud.githubusercontent.com/assets/10714776/24757788/818830b4-1ae0-11e7-98b4-0894ff7ea147.png)

while if i look on trakt.tv itselve it does show one play for this episode
![image](https://cloud.githubusercontent.com/assets/10714776/24757827/a22fd9ca-1ae0-11e7-9485-d1d31ed7bb47.png)

so traktflix is not to blame, i will check this tonight at home at see what i get there

**Comment by tegon** [comment] 2017-04-06 16:12
Yeah, that is really odd. The only thing that I imagine may be causing this is if you were logged in different Trakt.tv accounts - or Netflix profiles - at your home and work. But I assume that's not the case right?

**Comment by joyrider3774** [comment] 2017-04-06 16:50
I have only one trakt.tv account using facebook login. I have one netflix account but it does have multiple profiles but i'm always making sure that when i log in to netflix and use traktflix for syncing that the same profile is chosen before i go to account settings and select history so as far as i'm aware i'm using the same ones at work and home for bith netflix and trakt. My other profiles dont show, as far as i'm aware the viewing history of other profiles so i'm pretty sure i'm using same ones at work and home. 

One thing i did not try at work yet is clearing chrome's cache and reinstalling traktflix. I did try logging out and logging in again at work. I'll reply when i get home, am on my way now

**Comment by joyrider3774** [comment] 2017-04-06 17:22
this is the result from home where it works, same id (episode) does get at a result from trakt api but does not at work. i'm using same netflix account and profile as i did on work..
![image](https://cloud.githubusercontent.com/assets/10714776/24767096/24a00c3c-1afe-11e7-9ce5-0a1f852f3216.png)

I'll clear cache etc and try a few things at work tommorow. But now that i know the issue happens at work i'll make sure to synchronize at home in the future. But still might be good that i check a few things at work to see what might causing it / fixes it in case others ever have the issue

**Comment by joyrider3774** [comment] 2017-04-07 09:21
@tegon i fixed it at work by clearing the cache / cookies / tempory internet files etc of chrome and logging in / out of trakt.tv in the plugin

So it seems there might be issues with requests that are cached somehow .. now it displays the dates and same data at work also.

As far i'm concerned my problem is solved but still it's weird it was showing cached data somehow (don't know why else clearing cache would have solved it)

**Comment by tegon** [comment] 2017-04-07 19:51
Thanks for checking this out. I'm going to close this since it was not a bug in the codebase.

**Closed by tegon** 2017-04-07 19:51 UTC
