### ISSUE TITLE
Incorrect scrobble time

### ISSUE THREAD

**Issue by SITZ** [tegon/traktflix#19] opened 2016-01-09 12:11 UTC
It looks like some episodes were scrobbled with incorrect timestamp.
I watched it recently in January '16 but the scrobble date on trakt.tv appears to be August 1st, 2016.
Is it a change in trakt.tv API? How can this be fixed somehow?

**Comment by MrMamen** [comment] 2016-01-10 00:28
Probably a duplicate of #13 (It is parsed the wrong way due to localized settings. [Setting the language](https://www.netflix.com/LanguagePreferences) to English might help depending on region.)

**Comment by SITZ** [comment] 2016-01-10 05:44
It's already set to English so, that shouldn't be the reason.
Though, here is the pattern. Scrobble on January 9th shows the date of
August 1st and Scrobble on January 10th shows that of September 1st 00:00
UTC.
Hmm, day and month pattern is screwed in scrobbles?

Thanks & Regards,
- Sitesh Shrivastava

**Comment by tegon** [comment] 2016-01-11 10:45
If your date is in DD/MM/YYYY format, it is a duplicate of #13. For now, only USA date formats are supported (MM/DD/YYYY).
Also, please change the name of the issue, as this is related to the Sync history feature instead of scrobble.

**Comment by tegon** [comment] 2016-01-31 18:40
Fixed on v1.0.5.5.

**Closed by tegon** 2016-01-31 18:40 UTC
