### ISSUE TITLE
History not loading anymore

### ISSUE THREAD

**Issue by andreifilip** [tegon/traktflix#98] opened 2019-03-09 06:37 UTC
First of all, thanks a lot for this great extension...
Now, my problem:

I've watched lots of episodes from my Android device, and starting a few days ago the history page keeps loading over and over (it's stuck ok Loading page 1...)

1 Log into traktflix
2 Click the 'History' tab in the chrome widget
3 Loading indicator moves continuously and the page fails to load

I have the same problem on Firefox and Chrome also, using the latest 2.0.8 version

Thanks a lot

**Comment by cdj** [comment] 2019-03-09 08:02
Dupe of https://github.com/tegon/traktflix/issues/97 ?

**Comment by andreifilip** [comment] 2019-03-09 08:08
@cdj I think so,
Haven't got any firefox error, but the history page is stuck as described in #97, so sorry for this one

**Comment by andreifilip** [comment] 2019-03-09 10:32
Seems like chrome throw this error in Console:
`Uncaught TypeError: Cannot read property '80011291' of undefined
    at history-sync.js:6
    at Array.map (<anonymous>)
    at XMLHttpRequest.success (history-sync.js:6)
    at XMLHttpRequest.i.onload (history-sync.js:1)`

**Comment by gsrafael01** [comment] 2019-03-09 10:42
Yeah, it's the same error.

**Closed** 2019-03-09 10:42 UTC
Labels: duplicate
